//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FansResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FansResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.FansResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicione sua equipe.
        /// </summary>
        internal static string AddYourTeam {
            get {
                return ResourceManager.GetString("AddYourTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seja  único.
        /// </summary>
        internal static string BeUnique {
            get {
                return ResourceManager.GetString("BeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clique para ser único para sempre.
        /// </summary>
        internal static string ClickBeUnique {
            get {
                return ResourceManager.GetString("ClickBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clique no botão PayPal para ver como é fácil e barato  se tornar parte da história do seu clube!.
        /// </summary>
        internal static string ClickPayPal {
            get {
                return ResourceManager.GetString("ClickPayPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contato.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Exemplo.
        /// </summary>
        internal static string ExampleTeam {
            get {
                return ResourceManager.GetString("ExampleTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sempre.
        /// </summary>
        internal static string Forever {
            get {
                return ResourceManager.GetString("Forever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torne-se parte da história do seu clube!.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esqueci sua equipe?.
        /// </summary>
        internal static string MissYourTeam {
            get {
                return ResourceManager.GetString("MissYourTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal. Encontramos essas equipes.
        /// </summary>
        internal static string Nice {
            get {
                return ResourceManager.GetString("Nice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pague com paypal.
        /// </summary>
        internal static string PayWithPaypal {
            get {
                return ResourceManager.GetString("PayWithPaypal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envie-nos um e-mail com o nome de sua equipe - você vai ser o primeiro fã!.
        /// </summary>
        internal static string SendUsEmail {
            get {
                return ResourceManager.GetString("SendUsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite seu time.
        /// </summary>
        internal static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termos de uso.
        /// </summary>
        internal static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite Novamente.
        /// </summary>
        internal static string TypeAgain {
            get {
                return ResourceManager.GetString("TypeAgain", resourceCulture);
            }
        }
    }
}
