//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Index", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Futebol.
        /// </summary>
        internal static string CategoryOne {
            get {
                return ResourceManager.GetString("CategoryOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrida.
        /// </summary>
        internal static string CategoryThree {
            get {
                return ResourceManager.GetString("CategoryThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basquete.
        /// </summary>
        internal static string CategoryTwo {
            get {
                return ResourceManager.GetString("CategoryTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mais Categorias....
        /// </summary>
        internal static string MoreCategories {
            get {
                return ResourceManager.GetString("MoreCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envie sua foto. &lt;br/&gt;
        ///                    Pode ser do jeito que você quiser.&lt;br/&gt;
        ///                    De uma final inesquecível.&lt;br/&gt;
        ///                    Com a camisa do seu time de coração.&lt;br/&gt;
        ///                    Ou com sua tatuagem homenageando seu clube.&lt;br/&gt;
        ///                    Vale qualquer coisa!.
        /// </summary>
        internal static string PromoDescriptionOne {
            get {
                return ResourceManager.GetString("PromoDescriptionOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envie sua foto.&lt;br/&gt;
        ///                    Pode ser sua ou de algum familiar seu. Do jeito que você quiser.&lt;br /&gt;
        ///                    No clube, na praia, no campo, ou em qualquer outro lugar!.
        /// </summary>
        internal static string PromoDescriptionThree {
            get {
                return ResourceManager.GetString("PromoDescriptionThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PromoDescriptionTwo {
            get {
                return ResourceManager.GetString("PromoDescriptionTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ache seu esporte favorito..
        /// </summary>
        internal static string PromoExplanation1 {
            get {
                return ResourceManager.GetString("PromoExplanation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encontre seu time..
        /// </summary>
        internal static string PromoExplanation2 {
            get {
                return ResourceManager.GetString("PromoExplanation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eternize sua imagem e seja um dos 30 maiores fans!.
        /// </summary>
        internal static string PromoExplanation3 {
            get {
                return ResourceManager.GetString("PromoExplanation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os Top 30 Fans.
        /// </summary>
        internal static string PromoTitleExplanation {
            get {
                return ResourceManager.GetString("PromoTitleExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meu time. Meu sonho..
        /// </summary>
        internal static string PromoTitleOne {
            get {
                return ResourceManager.GetString("PromoTitleOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 Fans. Um seleto grupo..
        /// </summary>
        internal static string PromoTitleThree {
            get {
                return ResourceManager.GetString("PromoTitleThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parte da história do meu time!.
        /// </summary>
        internal static string PromoTitleTwo {
            get {
                return ResourceManager.GetString("PromoTitleTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seja famoso. Seja um dos 30 maiores fans!.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
